"""Add organization column to user table

Revision ID: e0102047cdfb
Revises: 0a3993734aa2
Create Date: 2017-02-23 11:04:41.816168

"""

# revision identifiers, used by Alembic.
revision = 'e0102047cdfb'
down_revision = '0a3993734aa2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('organization', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'organization')
    ### end Alembic commands ###
